version: '3.2'
services:
  redis:
    image: redis:alpine
    container_name: snce-redis
    ports:
      - '${REDIS_PORT}:${REDIS_PORT}'

  mongodb:
    container_name: snce-mongoDB
    image: mongo:latest
    restart: always
    volumes:
      - ./pokeData:/data/db
    environment:
      - MONGO_INITDB_DATABASE= Pokemon
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
  # webserver:
  #   image: nginx:alpine
  #   container_name: snce-docker-webserver
  #   working_dir: /application
  #   environment:
  #     SYMFONY_ENV: ${SYMFONY_ENV}
  #   volumes:
  #     - .:/application:cached
  #     - ./docker-config/nginx/nginx_dev_snce.conf:/etc/nginx/conf.d/default.conf
  #   ports:
  #     - '8080:80'
  #   links:
  #     - php-fpm
