version: "3.2"
services:
  redis:
    image: redis:alpine
    container_name: snce-docker-redis
    ports:
      - "6379:6379"

  mysql:
    image: mysql:${DB_VERSION}
    container_name: snce-docker-mysql
    volumes:
      - .${DB_DATA}:/var/lib/mysql:cached
      - ./docker-config/mysql:/etc/mysql/conf.d
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    ports:
      - "${DB_PORT}:3306"

  webserver:
    image: nginx:alpine
    container_name: snce-docker-webserver
    working_dir: /application
    environment:
      SYMFONY_ENV: ${SYMFONY_ENV}
    volumes:
      - .:/application:cached
      - ./docker-config/nginx/nginx_dev_snce.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    links:
      - php-fpm

  php-fpm:
    build:
      context: ./docker-config/php-fpm
      args:
        - xdebug=${XDEBUG}
    container_name: snce-docker-php-fpm
    working_dir: /application
    environment:
      SYMFONY_ENV: ${SYMFONY_ENV}
      XDEBUG: ${XDEBUG}
      XDEBUG_HOST: ${XDEBUG_HOST}
      PHP_TIMEZONE: ${PHP_TIMEZONE}
      PHP_DISPLAY_ERRORS: ${PHP_DISPLAY_ERRORS}
    volumes:
      - .:/application:cached
      - ./docker-config/php-fpm/php-ini-overrides.ini:/usr/local/etc/php/conf.d/98-overrides.ini
      - ./docker-config/php-fpm/www-custom.conf:/usr/local/etc/php-fpm.d/www-custom.conf

    links:
      - mysql
      - redis
